/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerLifycycleRouteImport } from './routes/worker-lifycycle'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user/$Id'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPlansRouteImport } from './routes/settings/plans'
import { Route as SettingsPaymentsRouteImport } from './routes/settings/payments'
import { Route as SettingsEmployeesRouteImport } from './routes/settings/employees'
import { Route as SettingsDocumentsRouteImport } from './routes/settings/documents'
import { Route as PasswordResetRouteImport } from './routes/password/reset'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as FragebogenTokenRouteImport } from './routes/fragebogen/$token'
import { Route as SettingsTemplatesTemplateRouteImport } from './routes/settings/templates/template'
import { Route as SettingsTemplatesIdRouteImport } from './routes/settings/templates/$id'
import { Route as SettingsDocumentsIdRouteImport } from './routes/settings/documents/$id'
import { Route as EmailVerifyCodeRouteImport } from './routes/email/verify/$code'

const WorkerLifycycleRoute = WorkerLifycycleRouteImport.update({
  id: '/worker-lifycycle',
  path: '/worker-lifycycle',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$Id',
  path: '/user/$Id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPlansRoute = SettingsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmployeesRoute = SettingsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDocumentsRoute = SettingsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => SettingsRoute,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FragebogenTokenRoute = FragebogenTokenRouteImport.update({
  id: '/fragebogen/$token',
  path: '/fragebogen/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTemplatesTemplateRoute =
  SettingsTemplatesTemplateRouteImport.update({
    id: '/templates/template',
    path: '/templates/template',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsTemplatesIdRoute = SettingsTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDocumentsIdRoute = SettingsDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsDocumentsRoute,
} as any)
const EmailVerifyCodeRoute = EmailVerifyCodeRouteImport.update({
  id: '/email/verify/$code',
  path: '/email/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/fragebogen/$token': typeof FragebogenTokenRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/settings/documents': typeof SettingsDocumentsRouteWithChildren
  '/settings/employees': typeof SettingsEmployeesRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/plans': typeof SettingsPlansRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
  '/settings/documents/$id': typeof SettingsDocumentsIdRoute
  '/settings/templates/$id': typeof SettingsTemplatesIdRoute
  '/settings/templates/template': typeof SettingsTemplatesTemplateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/fragebogen/$token': typeof FragebogenTokenRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/settings/documents': typeof SettingsDocumentsRouteWithChildren
  '/settings/employees': typeof SettingsEmployeesRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/plans': typeof SettingsPlansRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
  '/settings/documents/$id': typeof SettingsDocumentsIdRoute
  '/settings/templates/$id': typeof SettingsTemplatesIdRoute
  '/settings/templates/template': typeof SettingsTemplatesTemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/fragebogen/$token': typeof FragebogenTokenRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/settings/documents': typeof SettingsDocumentsRouteWithChildren
  '/settings/employees': typeof SettingsEmployeesRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/plans': typeof SettingsPlansRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
  '/settings/documents/$id': typeof SettingsDocumentsIdRoute
  '/settings/templates/$id': typeof SettingsTemplatesIdRoute
  '/settings/templates/template': typeof SettingsTemplatesTemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/worker-lifycycle'
    | '/fragebogen/$token'
    | '/password/forgot'
    | '/password/reset'
    | '/settings/documents'
    | '/settings/employees'
    | '/settings/payments'
    | '/settings/plans'
    | '/settings/profile'
    | '/user/$Id'
    | '/email/verify/$code'
    | '/settings/documents/$id'
    | '/settings/templates/$id'
    | '/settings/templates/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/worker-lifycycle'
    | '/fragebogen/$token'
    | '/password/forgot'
    | '/password/reset'
    | '/settings/documents'
    | '/settings/employees'
    | '/settings/payments'
    | '/settings/plans'
    | '/settings/profile'
    | '/user/$Id'
    | '/email/verify/$code'
    | '/settings/documents/$id'
    | '/settings/templates/$id'
    | '/settings/templates/template'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/worker-lifycycle'
    | '/fragebogen/$token'
    | '/password/forgot'
    | '/password/reset'
    | '/settings/documents'
    | '/settings/employees'
    | '/settings/payments'
    | '/settings/plans'
    | '/settings/profile'
    | '/user/$Id'
    | '/email/verify/$code'
    | '/settings/documents/$id'
    | '/settings/templates/$id'
    | '/settings/templates/template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRoute
  WorkerLifycycleRoute: typeof WorkerLifycycleRoute
  FragebogenTokenRoute: typeof FragebogenTokenRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordResetRoute: typeof PasswordResetRoute
  UserIdRoute: typeof UserIdRoute
  EmailVerifyCodeRoute: typeof EmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-lifycycle': {
      id: '/worker-lifycycle'
      path: '/worker-lifycycle'
      fullPath: '/worker-lifycycle'
      preLoaderRoute: typeof WorkerLifycycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$Id': {
      id: '/user/$Id'
      path: '/user/$Id'
      fullPath: '/user/$Id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/plans': {
      id: '/settings/plans'
      path: '/plans'
      fullPath: '/settings/plans'
      preLoaderRoute: typeof SettingsPlansRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/employees': {
      id: '/settings/employees'
      path: '/employees'
      fullPath: '/settings/employees'
      preLoaderRoute: typeof SettingsEmployeesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/documents': {
      id: '/settings/documents'
      path: '/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof SettingsDocumentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragebogen/$token': {
      id: '/fragebogen/$token'
      path: '/fragebogen/$token'
      fullPath: '/fragebogen/$token'
      preLoaderRoute: typeof FragebogenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/templates/template': {
      id: '/settings/templates/template'
      path: '/templates/template'
      fullPath: '/settings/templates/template'
      preLoaderRoute: typeof SettingsTemplatesTemplateRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/templates/$id': {
      id: '/settings/templates/$id'
      path: '/templates/$id'
      fullPath: '/settings/templates/$id'
      preLoaderRoute: typeof SettingsTemplatesIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/documents/$id': {
      id: '/settings/documents/$id'
      path: '/$id'
      fullPath: '/settings/documents/$id'
      preLoaderRoute: typeof SettingsDocumentsIdRouteImport
      parentRoute: typeof SettingsDocumentsRoute
    }
    '/email/verify/$code': {
      id: '/email/verify/$code'
      path: '/email/verify/$code'
      fullPath: '/email/verify/$code'
      preLoaderRoute: typeof EmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsDocumentsRouteChildren {
  SettingsDocumentsIdRoute: typeof SettingsDocumentsIdRoute
}

const SettingsDocumentsRouteChildren: SettingsDocumentsRouteChildren = {
  SettingsDocumentsIdRoute: SettingsDocumentsIdRoute,
}

const SettingsDocumentsRouteWithChildren =
  SettingsDocumentsRoute._addFileChildren(SettingsDocumentsRouteChildren)

interface SettingsRouteChildren {
  SettingsDocumentsRoute: typeof SettingsDocumentsRouteWithChildren
  SettingsEmployeesRoute: typeof SettingsEmployeesRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsPlansRoute: typeof SettingsPlansRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTemplatesIdRoute: typeof SettingsTemplatesIdRoute
  SettingsTemplatesTemplateRoute: typeof SettingsTemplatesTemplateRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDocumentsRoute: SettingsDocumentsRouteWithChildren,
  SettingsEmployeesRoute: SettingsEmployeesRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsPlansRoute: SettingsPlansRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTemplatesIdRoute: SettingsTemplatesIdRoute,
  SettingsTemplatesTemplateRoute: SettingsTemplatesTemplateRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  WorkerLifycycleRoute: WorkerLifycycleRoute,
  FragebogenTokenRoute: FragebogenTokenRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordResetRoute: PasswordResetRoute,
  UserIdRoute: UserIdRoute,
  EmailVerifyCodeRoute: EmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
