/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as LoginRouteImport } from './routes/login';
import { Route as HandwerkerRouteImport } from './routes/handwerker';
import { Route as IndexRouteImport } from './routes/index';
import { Route as UserIdRouteImport } from './routes/user/$Id';
import { Route as ProfileProfileRouteImport } from './routes/profile/profile';
import { Route as PasswordResetRouteImport } from './routes/password/reset';
import { Route as PasswordForgotRouteImport } from './routes/password/forgot';
import { Route as DashboardCeoRouteImport } from './routes/dashboard/ceo';
import { Route as EmailVerifyCodeRouteImport } from './routes/email/verify/$code';
const SignupRoute = SignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const HandwerkerRoute = HandwerkerRouteImport.update({
    id: '/handwerker',
    path: '/handwerker',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const UserIdRoute = UserIdRouteImport.update({
    id: '/user/$Id',
    path: '/user/$Id',
    getParentRoute: () => rootRouteImport,
});
const ProfileProfileRoute = ProfileProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProfileRoute,
});
const PasswordResetRoute = PasswordResetRouteImport.update({
    id: '/password/reset',
    path: '/password/reset',
    getParentRoute: () => rootRouteImport,
});
const PasswordForgotRoute = PasswordForgotRouteImport.update({
    id: '/password/forgot',
    path: '/password/forgot',
    getParentRoute: () => rootRouteImport,
});
const DashboardCeoRoute = DashboardCeoRouteImport.update({
    id: '/dashboard/ceo',
    path: '/dashboard/ceo',
    getParentRoute: () => rootRouteImport,
});
const EmailVerifyCodeRoute = EmailVerifyCodeRouteImport.update({
    id: '/email/verify/$code',
    path: '/email/verify/$code',
    getParentRoute: () => rootRouteImport,
});
const ProfileRouteChildren = {
    ProfileProfileRoute: ProfileProfileRoute,
};
const ProfileRouteWithChildren = ProfileRoute._addFileChildren(ProfileRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    HandwerkerRoute: HandwerkerRoute,
    LoginRoute: LoginRoute,
    ProfileRoute: ProfileRouteWithChildren,
    SettingsRoute: SettingsRoute,
    SignupRoute: SignupRoute,
    DashboardCeoRoute: DashboardCeoRoute,
    PasswordForgotRoute: PasswordForgotRoute,
    PasswordResetRoute: PasswordResetRoute,
    UserIdRoute: UserIdRoute,
    EmailVerifyCodeRoute: EmailVerifyCodeRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
